Cams.Web.MVCRazor/Models/BusinessRegistration/BusinessRegistrationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Cams.Common.Dto.ClientRegistration;
using Cams.Web.MVCRazor.Models.Shared;

namespace Cams.Web.MVCRazor.Models.BusinessRegistration
{
    public class BusinessRegistrationModel: ClientDto
    {
        #region Constructor
        public BusinessRegistrationModel()
        {
            CompanyAddress = new AddressReadOnlyViewModel("");
            CompanyContacts = new ContactsReadOnlyViewModel("");
            PrimaryContactsAddress = new AddressReadOnlyViewModel("PCP");
            PrimaryContactsContacts = new ContactsReadOnlyViewModel("PCP");
            PrimaryContactsContacts.IsWebsiteApplicable = false;
            ApmcAddress = new AddressReadOnlyViewModel("APMC");
            ApmcContacts = new ContactsReadOnlyViewModel("APMC");
            
            base.ClientPrimaryContactPerson = new ClientPrimaryContactPersonDto { 
                ClientPrimaryContactPersonDesignation = new Common.Dto.User.DesignationDto()
            };

            base.ClientAPMC = new Common.Dto.Masters.APMCDto();
        }
        #endregion

        #region Properties
        public int hdnCurrentTab { get; set; }
        public AddressReadOnlyViewModel CompanyAddress;
        public ContactsReadOnlyViewModel CompanyContacts;
        public AddressReadOnlyViewModel PrimaryContactsAddress;
        public ContactsReadOnlyViewModel PrimaryContactsContacts;
        public AddressReadOnlyViewModel ApmcAddress;
        public ContactsReadOnlyViewModel ApmcContacts;
        #endregion

        #region Static Methods

        #endregion
    }
}

Cams.Web.MVCRazor/Controllers/BusinessRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cams.Web.MVCRazor.Models.BusinessRegistration;
using Cams.Common.Dto.ClientRegistration;
using AutoMapper;
using Cams.Common;
using Cams.Common.Dto.User;

namespace Cams.Web.MVCRazor.Controllers
{
    public partial class BusinessRegistrationController : CommonController
    {
        //
        // GET: /BusinessRegistration/

        public ActionResult BusinessRegistrationIndex()
        {
            BusinessRegistrationModel model = GetBusinessRegistrationModelFromSession();
            model.hdnCurrentTab = Session["BRActiveTab"] != null ? Convert.ToInt32(Session["BRActiveTab"]) : 0;
            UserDto userDto= (UserDto)Session[Constants.SKCURRENTUSER];
            int caId= Convert.ToInt32( Helper.GetCAIdOfUser(userDto));
            ClientDto clientDto = GetClient(caId, false);

            model = Mapper.Map<ClientDto, BusinessRegistrationModel>(clientDto);  
          
            //model.ClientAddress = clientDto.ClientAddress;
            //model.ClientAPMC = clientDto.ClientAPMC;
            //model.ClientBusinessConstitution = clientDto.ClientBusinessConstitution;
            //model.ClientCommodities = clientDto.ClientCommodities;
            //model.ClientContacts = clientDto.ClientContacts;
            //model.ClientPartners = clientDto.ClientPartners;
            //model.ClientPhoneCharges = clientDto.ClientPhoneCharges;
            //model.ClientPrimaryContactPerson = clientDto.ClientPrimaryContactPerson;
            //model.ClientSisterConcerns = clientDto.ClientSisterConcerns;
            //model.ClientSubscription = clientDto.ClientSubscription;
            //model.ClientTaxationAndLicenses = clientDto.ClientTaxationAndLicenses;

            //model.CompanyAddress.Address = clientDto.ClientAddress;
            //model.CompanyContacts.Contacts = clientDto.ClientContacts;
            //model.CompanyContacts.Email1 = clientDto.Email1;
            //model.CompanyContacts.Email2 = clientDto.Email2;            
            //model.CompanyContacts.Website= clientDto.Website;
                        
            //if (clientDto.ClientPrimaryContactPerson != null)
            //{
            //    model.PrimaryContactsContacts.Email1 = clientDto.ClientPrimaryContactPerson.Email1;
            //    model.PrimaryContactsContacts.Email1 = clientDto.ClientPrimaryContactPerson.Email2; 
            //    if(clientDto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress != null)
            //        model.PrimaryContactsAddress.Address = clientDto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress;
            //    if(clientDto.ClientPrimaryContactPerson.ClientPrimaryContacts != null)
            //        model.PrimaryContactsContacts.Contacts = clientDto.ClientPrimaryContactPerson.ClientPrimaryContacts;
            //}
                          
            
            //if (clientDto.ClientAPMC != null)
            //{
            //    model.ApmcContacts.Email1 = clientDto.ClientAPMC.Email1;
            //    model.ApmcContacts.Email2 = clientDto.ClientAPMC.Email2;
            //    model.ApmcContacts.Website = clientDto.ClientAPMC.Website;

            //    if(clientDto.ClientAPMC.Address != null)
            //        model.ApmcAddress.Address = clientDto.ClientAPMC.Address;
            //    if(clientDto.ClientAPMC.ContactNos != null)
            //        model.ApmcContacts.Contacts = clientDto.ClientAPMC.ContactNos;
            //}
            
            return View("BusinessProfile", model);
        }

        private BusinessRegistrationModel GetBusinessRegistrationModelFromSession()
        {
            BusinessRegistrationModel brModel;
            if (Session["BusinessRegistrationModel"] != null)
                brModel = (BusinessRegistrationModel)Session["BusinessRegistrationModel"];
            else
                brModel = new BusinessRegistrationModel();
            return brModel;
        }

    }
}

Cams.Web.MVCRazor/Controllers/ClientAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cams.Common.Message;
using Cams.Web.MVCRazor.APMCMasterServiceReference;
using Cams.Web.MVCRazor.Helpers;
using Cams.Common;
using Cams.Web.MVCRazor.Models.ClientRegistration;
using Cams.Web.MVCRazor.Models.Shared;
using Cams.Web.MVCRazor.ClientServiceReference;
using Cams.Common.Dto.User;
using Cams.Common.Dto.ClientRegistration;
using Cams.Common.Dto;
using DevExpress.Web.Mvc;
using Cams.Common.Dto.Masters;
using Cams.Web.MVCRazor.DesignationServiceReference;
using Cams.Common.Querying;
using Cams.Web.MVCRazor.BusinessConstitutionServiceReference;
using Cams.Web.MVCRazor.CityVillageServiceReference;
using Cams.Common.Dto.ClientMasters;

namespace Cams.Web.MVCRazor.Controllers
{
    public partial class ClientAccountController : CommonController
    {
        //string mode = string.Empty;
        private bool hasWarnings = true;
        private bool isModelStateValid;
        private ClientRegistrationModel modelClientRegistration;

        #region Client Welcome Page
        [CamsAuthorize(Roles = Constants.MANAGECLIENTUSERS, Permissions = CamsAuthorizeAttribute.RolePermission.View)]
        public ActionResult ClientWelcome()
        {
            return View("ClientWelcome");
        }
        #endregion

        #region Clients List
        public ActionResult ClientsIndex()
        {
            ClientsModel model = new ClientsModel();
            model.Clients = GetClientList();
            return View("Clients", model);
        }

        public ActionResult GetClients()
        {
            return PartialView("ClientsGridView", GetClientList());
        }

        public List<ClientDto> GetClientList()
        {
            Query query = new Query();
            ClientServiceReference.ClientServiceClient client = new ClientServiceReference.ClientServiceClient();
            var Clients = client.FindByQuery(query, true);
            client.Close();
            return Clients.Entities.ToList();
        }
        #endregion

        #region Client Registration
        [CamsAuthorize(Roles = Constants.CLIENTREGISTRATION, Permissions = CamsAuthorizeAttribute.RolePermission.Add)]
        public ActionResult ClientRegistrationPageLoad()
        {
            ClientRegistrationModel model = new ClientRegistrationModel();
            model.hdnCurrentTab = 0;
            RemoveClientRegistrationSessions();
            Session["ClientSubscriptionPaymentDetailsModel"] = model.ClientSubscriptionPaymentDetailsModel;
            return View("CompanyProfile", model);
        }

        #region EditClientIndex
        [CamsAuthorize(Roles = Constants.MANAGEACKUSERS + "," + Constants.MANAGECLIENTUSERS
            , Permissions = CamsAuthorizeAttribute.RolePermission.Update)]
        public ActionResult EditClientIndex()
        {
            ClientRegistrationModel model = new ClientRegistrationModel();
            RemoveClientRegistrationSessions();

            if (Request.QueryString["mode"] != null)
            {
                model.mode = Request.QueryString["mode"].ToString();
            }
            int CAId = 0;
            if (Request.QueryString["caid"] != null)
            {
                CAId = Convert.ToInt32(Request.QueryString["caid"].ToString());
            }

            ClientServiceClient client = null;
            ClientDto clientdto = null;

            try
            {
                UserDto CurrentUser = (UserDto)Session[Constants.SKCURRENTUSER];
                if (CAId > 0)
                {
                    client = new ClientServiceClient();
                    clientdto = client.GetById(CAId);
                    if (clientdto != null && clientdto.AllowEdit)
                    {
                        #region Client Registration
                        // Session["ClientSubscriptionPaymentDetailsModel"] = null;

                        #region CompanyProfile
                        model.DisplayClientId = clientdto.DisplayClientId;
                        model.CompanyName = clientdto.CompanyName;
                        if (clientdto.IsActive && clientdto.RegistrationDate != null)
                        {
                            model.RegistrationDate = clientdto.RegistrationDate;
                        }
                        else
                        {
                            model.RegistrationDate = null;
                        }
                        model.Alias = clientdto.Alias;
                        model.PAN = clientdto.PAN;
                        model.TAN = clientdto.TAN;
                        model.Image = clientdto.Image;
                        model.Email1 = clientdto.Email1;
                        model.Email2 = clientdto.Email2;
                        model.Website = clientdto.Website;
                        model.IsActive = clientdto.IsActive;
                        model.IsDeleted = clientdto.IsDeleted;
                        model.Status = clientdto.Status;
                        model.AllowEdit = true;
                        model.APMCLicenseNo = clientdto.APMCLicenseNo;
                        model.APMCLicenseValidUpTo = clientdto.APMCLicenseValidUpTo;
                        model.NoOfPartners = clientdto.NoOfPartners;
                        model.TDSOnSubscriptionPayment = clientdto.TDSOnSubscriptionPayment;
                        model.AdditionalInfoForSubscriptionPayment = clientdto.AdditionalInfoForSubscriptionPayment;

                        model.CreatedBy = CurrentUser.UserId;
                        model.ModifiedBy = CurrentUser.UserId;
                        model.CreatedDate = DateTime.Now;
                        model.ModifiedDate = DateTime.Now;
                        #endregion

                        #region Company Profile Address & Contact
                        if (clientdto.ClientContacts != null)
                        {
                            model.ClientContacts = clientdto.ClientContacts;
                        }
                        if (clientdto.ClientAddress != null)
                        {
                            model.ClientAddress = clientdto.ClientAddress;
                            if (clientdto.ClientAddress.CityVillage != null)
                            {
                                model.StateDistrictPlacesControlNames[0].HiddenFieldForCityVillageValue = clientdto.ClientAddress.CityVillage.CityVillageId;
                                model.StateDistrictPlacesControlNames[0].HiddenFieldForDistrictValue = clientdto.ClientAddress.CityVillage.DistrictOfCityVillage.DistrictId;
                                model.StateDistrictPlacesControlNames[0].HiddenFieldForStateValue = clientdto.ClientAddress.CityVillage.DistrictOfCityVillage.StateOfDistrict.StateId;
                            }
                        }
                        #endregion

                        #region Client PrimaryContactPerson
                        if (clientdto.ClientPrimaryContactPerson != null)
                        {
                            model.ClientPrimaryContactPerson = clientdto.ClientPrimaryContactPerson;
                            if (clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress != null)
                            {
                                model.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress = clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress;
                                if (clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress.CityVillage != null)
                                {
                                    model.StateDistrictPlacesControlNames[1].HiddenFieldForCityVillageValue = clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress.CityVillage.CityVillageId;
                                    model.StateDistrictPlacesControlNames[1].HiddenFieldForDistrictValue = clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress.CityVillage.DistrictOfCityVillage.DistrictId;
                                    model.StateDistrictPlacesControlNames[1].HiddenFieldForStateValue = clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonAddress.CityVillage.DistrictOfCityVillage.StateOfDistrict.StateId;
                                }
                            }
                            if (clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonDesignation != null)
                            {
                                model.designationModel[0].SelectedId = clientdto.ClientPrimaryContactPerson.ClientPrimaryContactPersonDesignation.DesignationId;
                            }
                            model.dOBnAgeModellist[0].BindDate = clientdto.ClientPrimaryContactPerson.DateOfBirth != null ? Convert.ToDateTime(clientdto.ClientPrimaryContactPerson.DateOfBirth) : Helper.SetDefaultDate();
                        }
                        #endregion

                        #region Client APMC & Commodity Class
                        if (clientdto.ClientAPMC != null)
                        {
                            model.ClientAPMC = clientdto.ClientAPMC;
                            model.APMCId = clientdto.ClientAPMC.APMCId;
                            model.HiddenFieldForAPMCValue = model.APMCId;
                        }
                        if (clientdto.ClientCommodities != null)
                        {
                            model.ClientCommodities = clientdto.ClientCommodities;
                            model.CommodityClassDtoList.Where(dir1 => clientdto.ClientCommodities.Any(dir2 => dir2.CommodityClassId == dir1.CommodityClassId)).ToList().Update(e => e.IsActive = true);
                        }
                        #endregion

                        #region Client BusinessConstitution
                        if (clientdto.ClientBusinessConstitution != null)

Cams.Web.MVCRazor/Views/BusinessRegistration/APMCView.cshtml
@model Cams.Web.MVCRazor.Models.BusinessRegistration.BusinessRegistrationModel
@using Cams.Common.Dto.ClientMasters;
<div class="groupfieldset">
	<ul class="reset onecolfield fl">
		<li>
			<div class="fl">
				<label id="lblAPMC">
					APMC</label>
				<span class="non-editable-txt">@Model.ClientAPMC.Name</span></div>
			<div class="fl">
				<label id="lblAPMCLicenseNo" class="width165">
					APMC License No.</label>
				<span class="non-editable-txt">@Model.APMCLicenseNo</span>
			</div>
			@{
				var sLicenseDate = Model.APMCLicenseValidUpTo != null ? Convert.ToDateTime(Model.APMCLicenseValidUpTo).ToString(Cams.Common.Constants.DATEFORMATFORDISPAY) : "";
			}
			<div class="fl">
				<label id="lblValidupto">
					Valid upto</label>
				<span class="non-editable-txt">@sLicenseDate</span></div>
		</li>
	</ul>
</div>
<div id="divAPMCAdd" class="groupfieldset groupfieldsetcol fl">
	@Html.Partial("AddressReadOnlyView", Model.ApmcAddress)
</div>
<div id="divAPMCCnts" class="groupfieldset groupfieldsetcol fr">
	@Html.Partial("ContactsReadOnlyView", Model.ApmcContacts)
</div>
<div class="clr">
</div>
@{
	var sCommodities="";
	foreach (CommodityClassDto cl in Model.ClientCommodities)
	{
		sCommodities += cl.Name + ", ";
	}
	sCommodities = sCommodities.TrimEnd(' ');
	sCommodities=sCommodities.TrimEnd(',');
}
<div class="groupfieldset">
	<ul class="reset onecolfield fl">
		<li style="text-align: left;">
			<label id="lblCommodityClass">
				Commodity Class</label>
			<span class="non-editable-txt">@sCommodities</span></li>
	</ul>
</div>

Cams.Web.MVCRazor/Views/BusinessRegistration/AckAccountManagerView.cshtml
@using Cams.Web.MVCRazor
@model Cams.Common.Dto.User.UserDto

<div class="groupfieldset" style="min-height: 100px;">
	<ul class="reset onecolfield">
		<li>
			<label id="lblAMName" class="width75">@ClientResources.lblName</label>
			<span class="non-editable-txt">@Model.Name</span>			
		</li>		
		<li>
			<label id="lblAMEmail" class="width75">@ClientResources.lblEmail</label>
			<span class="non-editable-txt">@Model.Email</span>
		</li>
		<li>
			<label id="lblAMMobileNo" class="width75">@ClientResources.PIlblPIMobileNumber</label>
			<span class="non-editable-txt">@Model.MobileNo</span>
		</li>
	</ul>
	<div class="clr">
	</div>
</div>

Cams.Web.MVCRazor/Views/BusinessRegistration/BusinessProfile.cshtml
@model Cams.Web.MVCRazor.Models.BusinessRegistration.BusinessRegistrationModel
@using Cams.Web.MVCRazor
@using Cams.Common.Dto
@using Cams.Common
@using Cams.Web.MVCRazor.Helpers
@*Resources related to this page have extension BR*@
@{
	ViewBag.Title = "CompanyProfile";
	Layout = "~/Views/Shared/ClientMaster.cshtml";
}
@section Scripts
{
	<script src=@Url.Content("~/Scripts/JS/ContactDetails.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/JS/StateDistrictVillage.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/JS/UserDesignation.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/JS/DateOfBirth.js") type="text/javascript"></script>
	<script src=@Url.Content("~/Scripts/JS/CommonScript.js") type="text/javascript"></script>
	<script type="text/javascript">
		function SetAddressContactDivHeight(divCmpnyAddClientId, divCmpnyCntsClientId) {
			var divCmpnyAdd = $('#' + divCmpnyAddClientId);
			var divCmpnyCnts = $('#' + divCmpnyCntsClientId);
			var height = divCmpnyCnts.height();
			if (divCmpnyAdd.height() > height)
				height = divCmpnyAdd.height();

			divCmpnyAdd.height(height);
			divCmpnyCnts.height(height);
		}
	</script>
	<script type="text/javascript">

		var currentIndex;
		$(document).ready(function () {

			SetAddressContactDivHeight('divCompanyAddress', 'divCompanyContacts');
			SetAddressContactDivHeight('divPCPAdd', 'divPCPCnts');
			SetAddressContactDivHeight('divAPMCAdd', 'divAPMCCnts');
			SetAddressContactDivHeight('divSubDetailsLt', 'divSubDetailsRt');
			
			var currentIndex = $('#hdnCurrentTab').val();
			var activeTab = currentIndex;
			if (activeTab != null) {
				$("ul.tabs").tabs("div.panes > div.panes-data", {
					initialIndex: parseInt(activeTab),
					onBeforeClick: function (event, tabIndex) {
						currentIndex = this.getIndex();
						$('#hdnCurrentTab').val(parseInt(tabIndex));
						SaveTab(currentIndex);
					}
				});
			}
		});

		function SaveTab(tabIndex) {
			switch (tabIndex) {
				case 0: SaveCompanyProfile();
					break;
				case 1: SavePrimaryContactDetails();
					break;
				case 2: SaveAPMCDetails();
					break;
				case 3: SaveBusinessConstitution();
					break;
				case 4: SaveSubscriptionDetails();
					break;
				case 5: SavePaymentDetails();
					break;
				case 6: SaveAccountManager();
					break;
			}
		}

		function nextTab() {
			var currentIndex = $('#hdnCurrentTab').val();
			SaveTab(parseInt(currentIndex));
			var nextTabIndex = (currentIndex && currentIndex != '') ? parseInt(currentIndex) + 1 : 0;
			nextTabIndex = (nextTabIndex == 7) ? 6 : nextTabIndex
			$('#hdnCurrentTab').val(nextTabIndex);
			$("ul.tabs").tabs("div.panes > div.panes-data",
                {
                	initialIndex: parseInt(nextTabIndex)
                });
		}

		function previousTab() {
			var currentIndex = $('#hdnCurrentTab').val();
			SaveTab(parseInt(currentIndex));
			var prevTabIndex = (currentIndex && currentIndex != '') ? parseInt(currentIndex) - 1 : 0;
			prevTabIndex = (prevTabIndex == -1) ? 0 : prevTabIndex
			$('#hdnCurrentTab').val(prevTabIndex);
			$("ul.tabs").tabs("div.panes > div.panes-data",
                {
                	initialIndex: parseInt(prevTabIndex)
                });
		}
                      
	</script>
	<script type="text/javascript">
		$(document).ready(function () {
			//Set default open/close settings
			$('.acc_container_3').hide(); //Hide/close all containers
			$('.acc_trigger_3:first').addClass('active').next().show(); //Add "active" class to first trigger, then show/open the immediate next container
			//On Click
			$('.acc_trigger_3').click(function () {
				if ($(this).next().is(':hidden')) { //If immediate next container is closed...
					$('.acc_trigger_3').removeClass('active').next().slideUp(); //Remove all .acc_trigger classes and slide up the immediate next container
					$(this).toggleClass('active').next().slideDown(); //Add .acc_trigger class to clicked trigger and slide down the immediate next container
				}
				return false; //Prevent the browser jump to the link anchor
			});
		});
	</script>
}
@section PanelPartial
{
	<!-- the tabs -->
	<ul class="tabs">
		<li>
			<a href="#">@ClientResources.BRTabClientProfile</a>
		</li>
		<li>

		</li>
		<li>
			<a href="#">@ClientResources.BRTabTaxation</a></li>
		<li>
			<a href="#">@ClientResources.BRTabPhoneCharges</a></li>
		<li>
			<a href="#">@ClientResources.BRTabSisterConcerns</a></li>
	</ul>
}
@section MainBody
{
	<div class="page-data fl">
		@using (Html.BeginForm("BusinessRegistration", "BusinessRegistration", new { usertype = Request.QueryString["usertype"] }, FormMethod.Post, new { id = "BusinessRegistrationForm" }))
  {
			<div class="panes">
				<div class="panes-data">
					<h1>
						Business Profile</h1>
					<div class="Form-Wrap">
						<div class="container_3">
							<h2 class="acc_trigger_3 active">
								<a href="#">
									Company Profile</a></h2>
							<div class="acc_container_3" style="display: block;">
								@Html.Partial("ClientDetailsView", Model)
							</div>
						
							<h2 class="acc_trigger_3">
								<a href="#">
									APMC Details</a></h2>
							<div class="acc_container_3" style="display: block;">
								@Html.Partial("APMCView", Model)
							</div>
						
							<h2 class="acc_trigger_3">
								<a href="#">
									Primary Contact Person</a></h2>
							<div class="acc_container_3" style="display: block;">
								@Html.Partial("PrimaryContactPersonView", Model)
							</div>
							<h2 class="acc_trigger_3">
								<a href="#">
									ack' Relationship Account Manager</a></h2>
							<div class="acc_container_3" style="display: block;">
								@Html.Partial("AckAccountManagerView", Model.AccountManager)
							</div>
						
							
						</div>
					</div>
					<!--<div class="container_3">-->
						<h2 class="acc_trigger_3">
							<a href="#">@ClientResources.BRTabSubscription</a>
						</h2>
						<div class="acc_container_3" style="display: block;">
							@Html.Partial("AckSubscriptionDetailsView", Model)
						</div>
					<!--</div>-->
					<div class="clr">
					</div>
					<div class="clr">
					</div>
																																								<div>
					<table style="width: 100%">
						<tr>
							<td style="width: 20%">
								<ul class="reset input-botton" style="text-align: left;">
									<li>
										<a href="javascript:previousTab()">
											Previous</a>
									</li>
								</ul>
							</td>
							<td style="width: 60%">
								<ul class="reset input-botton" style="text-align: center;">
									<li>
										<br />
									</li>
									<li>
										<input type="submit" class="button_Save button_Submit" name="action:Save" value="" />
										<br />
										<div class="text-link">@ClientResources.CancelString&nbsp;
											@Html.ActionLink(ClientResources.CancelbtnText, "ClientsIndex", "ClientAccount")
										</div>
									</li>
								</ul>
							</td>
							<td style="width: 20%">
								<ul class="reset input-botton" style="text-align: right;">
									<li>
										<a href="javascript:nextTab()">
											Next</a>
									</li>
								</ul>
							</td>
						</tr>
					</table>
				</div>
					@Html.HiddenFor(model => model.hdnCurrentTab)
				</div>				
			</div>
  }
	</div>
}